### ISSUE TITLE
Detected vulnerability in ExcelJS

### ISSUE THREAD

**Issue by Siemienik** [Siemienik/xlsx-renderer#24]
Details: https://snyk.io/test/github/siemienik/xlsx-renderer#SNYK-JS-LODASH-567746

I created an issue for ExcelJS: https://github.com/exceljs/exceljs/issues/1250

**Comment by Siemienik** [comment]
currently, it isn't an important vulnerability

**Comment by mjsalinger** [comment]
Any way this can be revisited?  It is causing npm audit failures.

**Comment by Siemienik** [comment]
@mjsalinger Thank you for contact, It's nice to know that someone use my library:)

Of course, I will try to fix it asap. You made this issue the most important.

As can we see [here](https://snyk.io/test/github/siemienik/xlsx-renderer#SNYK-JS-LODASH-567746) this is not exactly the problem with xlsx-renderer but with some dependency, but I going to try to fix it there where it is possible.

**Comment by Siemienik** [comment]
Issues:
* ExcelJS : https://github.com/exceljs/exceljs/issues/1250
* Archiver: https://github.com/archiverjs/node-archiver/issues/419

**Comment by Siemienik** [comment]
@mjsalinger Done here: https://github.com/archiverjs/node-archiver/pull/420

We have to wait for releases for Archivizer and probably for ExcelJS.

**Comment by mjsalinger** [comment]
Thank you!

**Comment by Siemienik** [comment]
@mjsalinger https://github.com/archiverjs/node-archiver/pull/420 has been merged, I am waiting for a new version was published in npm. Next, I will update it in ExcelJS  (issue https://github.com/exceljs/exceljs/issues/1250)

If could I please you, please share with this lib with others, each star/watch/fork/npm download/git clone makes me really motivated 🥇 👍

**Comment by Siemienik** [comment]
@mjsalinger vulnerability was resolved
![image](https://user-images.githubusercontent.com/2893099/87235724-46225580-c3df-11ea-9b01-2f25cf67f075.png)

**Comment by Siemienik** [comment]
Hey, do you want to support my work? [**❤️ Sponsor me**](https://github.com/sponsors/Siemienik) 
Your issue is stuck? I can make it done, contact me for further info :)
